version: '1.0'
name: ReleasePipeline
displayName: ReleasePipeline
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - master
variables:
  GIT_USER: glnp
  GIT_EMAIL: guilin@goeasy.io
  GIT_PASS: 1qaz1234.gglnp
stages:
  - name: stage-c946720e
    displayName: 更新代码
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - '# 设置参数'
          - git remote rm origin
          - git remote add origin https://${GIT_USER}:${GIT_PASS}@gitee.com/goeasy-io/customer-support-live.git
          - ''
          - '# 清空老数据'
          - rm -rf *
          - ''
          - '# 克隆dev仓库,并切换分支'
          - git clone -b dist https://${GIT_USER}:${GIT_PASS}@gitee.com/goeasy-io/customer-support-dev.git
          - ''
          - ''
          - '# 复制新数据至live仓库'
          - cp -rf customer-support-dev/* ./
          - ''
          - '# 复制完毕删除目录'
          - rm -rf customer-support-dev
          - ''
          - '# 设置参数'
          - git config user.name "${GIT_USER}"
          - git config user.password "${GIT_PASS}"
          - git config user.email "${GIT_EMAIL}"
          - git config --global http.postBuffer 524288000
          - ''
          - '# 新仓库标记推送'
          - git add .
          - git commit -m 'Copy the development branch code to customer-support-live'
          - git push origin master
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
